// Shared helpers for the live page editor.
//
// Pure functions with no database imports, so components can use the key
// helpers without pulling the D1 layer into a bundle that doesn't need it.

/** Region keys are '<page>:<region>'. Normalised so casing can't fork a key. */
export const overrideKey = (key: string): string => key.trim().toLowerCase();

/** Page slug from a URL path: '/about' → 'about', '/' → 'home', '/a/b' → 'a-b'. */
export function pageSlug(pathname: string): string {
  const trimmed = pathname.replace(/^\/+|\/+$/g, '');
  return trimmed === '' ? 'home' : trimmed.replace(/\//g, '-');
}

/**
 * Whether the live editor should be active for this request.
 *
 * Both conditions are required: someone who may edit AND ?edit=1 in the URL.
 * The explicit switch matters — an editor browsing their own site normally
 * should see exactly what the public sees, not a page covered in edit
 * affordances they can trigger by mis-clicking.
 *
 * The first argument is `canEdit`, not "is signed in". A viewer account is
 * signed in and must still get the plain public page, with no edit handles and
 * no editor bar. This is the display half only — the save endpoint does its own
 * check, because anything that relies on the UI not offering a button is not a
 * permission check.
 */
export const isEditing = (url: URL, canEdit: boolean): boolean => canEdit && url.searchParams.get('edit') === '1';

/** Cap on a single region's length, enforced on both client and server. */
export const MAX_REGION_LENGTH = 5000;

/**
 * Derive a region key from the copy already in the template.
 *
 * The obvious alternative — numbering sections as they render — was rejected:
 * positional keys silently re-point when someone inserts a section above, so
 * edited copy would jump to the wrong heading. Keying on the source text means
 * a section keeps its override wherever it moves on the page, and an edit stays
 * attached to the thing it was written for.
 *
 * The trade-off is the reverse case: changing the *source* text in the .astro
 * file orphans any override made against the old text, and the page falls back
 * to the new source copy. That is the safer direction to fail in — a developer
 * changing the template usually means the new wording to win.
 *
 * `seen` disambiguates two sections that share identical source text on one
 * page, which is otherwise a silent collision where editing one changes both.
 */
export function regionKeyFrom(text: string, suffix: string, seen: Set<string>): string {
  const base =
    String(text)
      .replace(/<[^>]*>/g, ' ')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .split('-')
      .slice(0, 6)
      .join('-') || 'section';

  let key = `${base}-${suffix}`;
  let n = 2;
  while (seen.has(key)) key = `${base}-${n++}-${suffix}`;
  seen.add(key);
  return key;
}

/**
 * Region keys are generated by our own templates, so they always look like
 * 'page:region'. Validated anyway on the way in: the key is the primary key of
 * the table, and an unvalidated one lets a caller write unlimited junk rows.
 */
export const KEY_PATTERN = /^[a-z0-9][a-z0-9-]*:[a-z0-9][a-z0-9-]*$/;

/**
 * Best-effort URL for a region key, used only when the stored `path` is absent.
 *
 * It cannot be exact, and that is why the path is stored on the row instead:
 * pageSlug() flattens '/' to '-', so 'about-us' could have come from either
 * '/about-us' or '/about/us' and nothing in the key distinguishes them. This
 * guesses the single-segment reading, which is right for most pages and is only
 * ever reached for rows written before the path column existed.
 */
export const pathFromKey = (key: string): string => {
  const slug = key.split(':')[0];
  return slug === 'home' ? '/' : `/${slug}`;
};

/**
 * Narrow an untrusted value to a same-site path, or `fallback`.
 *
 * Used for the `?next=` parameter on sign-in and for the path the editor
 * reports when saving. Both are places where accepting an absolute URL would
 * hand the client's own domain to a phishing link.
 *
 * The second slash is what the lookahead rejects: '//evil.example' is a
 * protocol-relative URL that browsers follow off-site, and it passes a naive
 * "starts with /" check.
 */
export const safeInternalPath = (value: unknown, fallback = ''): string => {
  const path = String(value ?? '');
  return /^\/(?!\/)[^\s?#]*$/.test(path) ? path : fallback;
};
